---
branches:
  - name: main
# TODO: Remove; Might be useful to have some debug when attempting the first releases
debug: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: chore
          scope: deps
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: chore
            scope: deps
            section: Dependencies
  - "@semantic-release/github"
