---
branches:
  - name: main
# TODO: Remove; Might be useful to have some debug when attempting the first releases
debug: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
