---
name: Release
on:
  push:
    branches:
      - create-pr
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for cycjimmy/semantic-release-action to create release tags
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          token: ${{ secrets.STAS_RELEASE_TOKEN }}
      - uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # v3.2.0
        id: semantic-release
        with:
          dry_run: true
          extra_plugins: |
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.STAS_RELEASE_TOKEN }}
      - run: |
          echo $GITHUB_SHA > dummy.txt
      - uses: peter-evans/create-pull-request@v4
        if: steps.semantic-release.outputs.new_release_published == 'true'
